export default [
  {
    mapSeats: [
      {
        xCount: 7,
        yCount: 32,
        rows: [
          {
            row_number: "1",
            seats: [
              {
                available: true,
                seatNumber: "1A",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "1B",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "1C",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "2",
            seats: [
              {
                available: false,
                seatNumber: "2A",
                exists: true,
                rate: 0,
                currency: "",
              },
              {
                available: false,
                seatNumber: "2B",
                exists: true,
                rate: 0,
                currency: "",
              },
              {
                available: false,
                seatNumber: "2C",
                exists: true,
                rate: 0,
                currency: "",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "2D",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "2E",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "2F",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "3",
            seats: [
              {
                available: false,
                seatNumber: "3A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "3B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "3C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "3D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "3E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "3F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "4",
            seats: [
              {
                available: false,
                seatNumber: "4A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "4B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "4C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "4D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "4E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "4F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "5",
            seats: [
              {
                available: false,
                seatNumber: "5A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "5B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "5C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "5D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "5E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "5F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "6",
            seats: [
              {
                available: false,
                seatNumber: "6A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "6B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "6C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "6D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "6E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "6F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "7",
            seats: [
              {
                available: false,
                seatNumber: "7A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "7B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "7C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "7D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "7E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "7F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "8",
            seats: [
              {
                available: true,
                seatNumber: "8A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "8B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "8C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "8D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "8E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "8F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "9",
            seats: [
              {
                available: true,
                seatNumber: "9A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "9B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "9C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "9D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "9E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "9F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "10",
            seats: [
              {
                available: true,
                seatNumber: "10A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "10B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "10C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "10D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "10E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "10F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "11",
            seats: [
              {
                available: false,
                seatNumber: "11A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "11B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "11C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "11D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "11E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "11F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "12",
            seats: [
              {
                available: false,
                seatNumber: "12A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "12B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "12C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "12D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "12E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "12F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "13",
            seats: [
              {
                available: false,
                seatNumber: "13A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "13B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "13C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "13D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "13E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "13F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "14",
            seats: [
              {
                available: false,
                seatNumber: "14A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "14B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "14C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "14D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "14E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "14F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "15",
            seats: [
              {
                available: false,
                seatNumber: "15A",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "15B",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "15C",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "15D",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "15E",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "15F",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "16",
            seats: [
              {
                available: false,
                seatNumber: "16A",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "16B",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "16C",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "16D",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "16E",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "16F",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "17",
            seats: [
              {
                available: false,
                seatNumber: "17A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "17B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "17C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "17D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "17E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "17F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "18",
            seats: [
              {
                available: true,
                seatNumber: "18A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "18B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "18C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "18D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "18E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "18F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "19",
            seats: [
              {
                available: true,
                seatNumber: "19A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "19B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "19C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "19D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "19E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "19F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "20",
            seats: [
              {
                available: true,
                seatNumber: "20A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "20B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "20C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "20D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "20E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "20F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "21",
            seats: [
              {
                available: true,
                seatNumber: "21A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "21B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "21C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "21D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "21E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "21F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "22",
            seats: [
              {
                available: true,
                seatNumber: "22A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "22B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "22C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "22D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "22E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "22F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "23",
            seats: [
              {
                available: true,
                seatNumber: "23A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "23B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "23C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "23D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "23E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "23F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "24",
            seats: [
              {
                available: false,
                seatNumber: "24A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "24B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "24C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "24D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "24E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "24F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "25",
            seats: [
              {
                available: true,
                seatNumber: "25A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "25B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "25C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "25D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "25E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "25F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "26",
            seats: [
              {
                available: true,
                seatNumber: "26A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "26B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "26C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "26D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "26E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "26F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "27",
            seats: [
              {
                available: true,
                seatNumber: "27A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "27B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "27C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "27D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "27E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "27F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "28",
            seats: [
              {
                available: true,
                seatNumber: "28A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "28B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "28C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "28D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "28E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "28F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "29",
            seats: [
              {
                available: true,
                seatNumber: "29A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "29B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "29C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "29D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "29E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "29F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "30",
            seats: [
              {
                available: true,
                seatNumber: "30A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "30B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "30C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "30D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "30E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "30F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "31",
            seats: [
              {
                available: true,
                seatNumber: "31A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "31B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "31C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "31D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "31E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "31F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "32",
            seats: [
              {
                available: true,
                seatNumber: "32A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "32B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "32C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "32D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "32E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "32F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
        ],
      },
    ],
    lastName: "SHISHKOV",
    fullName: "ANDREI ALEKSANDROVICH",
    ticketNumber: 3166135669872,
    segmentIndex: 0,
    segmentsGroupIndex: 0,
  },
  {
    mapSeats: [
      {
        xCount: 7,
        yCount: 32,
        rows: [
          {
            row_number: "1",
            seats: [
              {
                available: true,
                seatNumber: "1A",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "1B",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "1C",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "2",
            seats: [
              {
                available: false,
                seatNumber: "2A",
                exists: true,
                rate: 0,
                currency: "",
              },
              {
                available: false,
                seatNumber: "2B",
                exists: true,
                rate: 0,
                currency: "",
              },
              {
                available: false,
                seatNumber: "2C",
                exists: true,
                rate: 0,
                currency: "",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "2D",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "2E",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "2F",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "3",
            seats: [
              {
                available: false,
                seatNumber: "3A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "3B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "3C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "3D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "3E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "3F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "4",
            seats: [
              {
                available: false,
                seatNumber: "4A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "4B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "4C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "4D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "4E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "4F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "5",
            seats: [
              {
                available: false,
                seatNumber: "5A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "5B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "5C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "5D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "5E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "5F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "6",
            seats: [
              {
                available: false,
                seatNumber: "6A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "6B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "6C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "6D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "6E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "6F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "7",
            seats: [
              {
                available: false,
                seatNumber: "7A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "7B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "7C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "7D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "7E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "7F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "8",
            seats: [
              {
                available: true,
                seatNumber: "8A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "8B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "8C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "8D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "8E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "8F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "9",
            seats: [
              {
                available: true,
                seatNumber: "9A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "9B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "9C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "9D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "9E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "9F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "10",
            seats: [
              {
                available: true,
                seatNumber: "10A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "10B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "10C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "10D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "10E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "10F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "11",
            seats: [
              {
                available: false,
                seatNumber: "11A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "11B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "11C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "11D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "11E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "11F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "12",
            seats: [
              {
                available: false,
                seatNumber: "12A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "12B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "12C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "12D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "12E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "12F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "13",
            seats: [
              {
                available: false,
                seatNumber: "13A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "13B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "13C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "13D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "13E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "13F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "14",
            seats: [
              {
                available: false,
                seatNumber: "14A",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "14B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "14C",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "14D",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "14E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "14F",
                exists: true,
                rate: 449,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "15",
            seats: [
              {
                available: false,
                seatNumber: "15A",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "15B",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "15C",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "15D",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "15E",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "15F",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "16",
            seats: [
              {
                available: false,
                seatNumber: "16A",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "16B",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "16C",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: false,
                seatNumber: "16D",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "16E",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "16F",
                exists: true,
                rate: 1000,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "17",
            seats: [
              {
                available: false,
                seatNumber: "17A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "17B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "17C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "17D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "17E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "17F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "18",
            seats: [
              {
                available: true,
                seatNumber: "18A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "18B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "18C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "18D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "18E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "18F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "19",
            seats: [
              {
                available: true,
                seatNumber: "19A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "19B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "19C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "19D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "19E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "19F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "20",
            seats: [
              {
                available: true,
                seatNumber: "20A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "20B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "20C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "20D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "20E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "20F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "21",
            seats: [
              {
                available: true,
                seatNumber: "21A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "21B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "21C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "21D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "21E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "21F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "22",
            seats: [
              {
                available: true,
                seatNumber: "22A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "22B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "22C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "22D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "22E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "22F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "23",
            seats: [
              {
                available: true,
                seatNumber: "23A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "23B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "23C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "23D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "23E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "23F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "24",
            seats: [
              {
                available: false,
                seatNumber: "24A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "24B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "24C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "24D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "24E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "24F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "25",
            seats: [
              {
                available: true,
                seatNumber: "25A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "25B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "25C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "25D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "25E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "25F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "26",
            seats: [
              {
                available: true,
                seatNumber: "26A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "26B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "26C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "26D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "26E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "26F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "27",
            seats: [
              {
                available: true,
                seatNumber: "27A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "27B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "27C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "27D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "27E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "27F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "28",
            seats: [
              {
                available: true,
                seatNumber: "28A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "28B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "28C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "28D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "28E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "28F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "29",
            seats: [
              {
                available: true,
                seatNumber: "29A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "29B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "29C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "29D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "29E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "29F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "30",
            seats: [
              {
                available: true,
                seatNumber: "30A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "30B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "30C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "30D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "30E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "30F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "31",
            seats: [
              {
                available: true,
                seatNumber: "31A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "31B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "31C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "31D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "31E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "31F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
          {
            row_number: "32",
            seats: [
              {
                available: true,
                seatNumber: "32A",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "32B",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "32C",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: false,
                seatNumber: "",
                exists: false,
                rate: "",
              },
              {
                available: true,
                seatNumber: "32D",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "32E",
                exists: true,
                rate: 349,
                currency: "РУБ",
              },
              {
                available: true,
                seatNumber: "32F",
                exists: true,
                rate: 399,
                currency: "РУБ",
              },
            ],
          },
        ],
      },
    ],
    lastName: "ALAKHVERDIEVA",
    fullName: "AILIN PAZILKYZY",
    ticketNumber: 3166136431632,
    segmentIndex: 0,
    segmentsGroupIndex: 0,
  },
];
